<?php
/**
 * ListingViolationSummaryApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Ebay\Sell\Compliance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Compliance API
 *
 * Service for providing information to sellers about their listings being non-compliant, or at risk for becoming non-compliant, against eBay listing policies.
 *
 * The version of the OpenAPI document: 1.4.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ebay\Sell\Compliance\Test\Api;

use \Ebay\Sell\Compliance\Configuration;
use \Ebay\Sell\Compliance\ApiException;
use \Ebay\Sell\Compliance\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ListingViolationSummaryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ebay\Sell\Compliance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListingViolationSummaryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getListingViolationsSummary
     *
     * .
     *
     */
    public function testGetListingViolationsSummary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
